# Netlify build configuration
[build]
  command = "gatsby build"
  publish = "public"
  functions = "netlify/functions"

# Rule to handle API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Rule to handle Single-Page App routing (for Gatsby)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200